//
// Created by Hesray on 2020/3/30.
//

#ifndef OPENCV_IMAGEPROC_H
#define OPENCV_IMAGEPROC_H

#endif //OPENCV_IMAGEPROC_H


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_ImageProc */

#ifndef _Included_com_demo_opencv_ImageProc
#define _Included_com_demo_opencv_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_opencv_ImageProc
 * Method:    trasformToGray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_demo_opencv__ImageProc_trasformToGray
        (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif